### ISSUE TITLE
Full migration to ReScript checklist

### ISSUE THREAD

**Issue by zth** [zth/rescript-relay#148]
This will play out over the coming months. Just keeping tabs on what needs to be done here and what stage it's at.

- [x] Able to read ReScript source in the compiler
- [x] Convert main ReasonRelay package files to ReScript
- [x] Docs converted to ReScript
- [x] Tests converted to ReScript
- [x] Dedicated VSCode extension converted to work on `res`
- [x] Make compiler output `res` files and syntax instead of `re`
- [x] Depend on `rescript-react` instead of `reason-react` Implemented here https://github.com/zth/reason-relay/pull/149
- [ ] Depend on (unreleased) `rescript-compiler` package instead of `bs-platform`
- [x] Change name to `rescript-relay`

**Comment by zth** [comment]
Converting the codegen to output `res` is worked on here: https://github.com/zth/reason-relay/pull/150/files

**Comment by zth** [comment]
We'll do one more release name ReasonRelay, and then fully rename to RescriptRelay 🚀

**Comment by zth** [comment]
This is considered done, as depending on an eventually renamed bs-platform will come naturally once that's released.
