### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by zth** [zth/rescript-relay#427]
Loose notes for a roadmap. This is WIP and not exhaustive right now.

## 2.0
Intended to be "incremental" and easy to adopt.
- [x] JSX v4 https://github.com/zth/rescript-relay/issues/421
- [x] Clean up PPX https://github.com/zth/rescript-relay/issues/389
- [x] M1 support for the PPX https://github.com/zth/rescript-relay/issues/380
- [x] Leverage optional fields syntax
- [x] Support uncurried

## 3.0
Intended to restructure underlying code a lot. As always as few breaking changes as possible, but there _will be breakages_ here.
- [x] Uncurried by default (might go into 1.5 depending on the timeline)
- [x] Remove "top level node field" transform
- [ ] Redo "conversion" functionality so it's understandable for other people than me, and easier to support more complex use cases. https://github.com/zth/rescript-relay/issues/407
- [x] Remove input object/variable makers (`makeVariables`, `make_someInputObject`). Adds complexity and isn't as needed now that the editor tooling of ReScript is a lot better
- [ ] ~~_Consider_ removing automatic conversion of custom scalars. I know people like this functionality, and I really do to, but it's adding an almost unreasonable amount of complexity to the compiler code, because of various reasons~~
- [x] Polyvariants -> variants for unions and enums? (if zero-cost variant runtime encoding lands in ReScript)
- [ ] ~~`Nullable.t` instead of runtime conversion to `Option` for all nullables in the generated types, now that we'll be able to pattern match on `Nullable.t`...?~~

**Comment by DZakh** [comment]
> Consider removing automatic conversion of custom scalars. I know people like this functionality, and I really do to, but it's adding an almost unreasonable amount of complexity to the compiler code, because of various reasons

Please no 😭
